name: corsac_jwt
version: 1.0.0-nullsafety.1
description: Lightweight implementation of JSON Web Tokens (JWT).
homepage: https://github.com/corsac-dart/jwt
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  asn1lib: ^1.0.0
  crypto: ^3.0.0
  ed25519_edwards: ^0.1.0
  logging: ^1.0.0
  pointycastle: ^3.0.0
  rsa_pkcs: ^2.0.0

dev_dependencies:
  coverage: ^1.0.0
  pedantic: ^1.11.0
  test: ^1.17.5


